name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check code formatting using Black
        uses: psf/black@stable
        with:
          options: "--diff --color --line-length 79"
          src: "./sidewinder"
      
      - name: Check import ordering using isort
        uses: isort/isort-action@master
        with:
          configuration: "--diff"
