name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isort/isort-action@master
      - uses: psf/black@stable
        with:
          options: "--check --diff --color --line-length 79"
          src: "./sidewinder"
